//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KatieStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
       
        public Purchase()
        {
            this.PurchaseProducts = new HashSet<PurchaseProduct>();
        }
    
        public int ID { get; set; }
        public string AspNetUserID { get; set; }
        public string OrderIdentifier { get; set; }
        public System.DateTime SubmittedDate { get; set; }
        public Nullable<System.DateTime> FulfilledDate { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<PurchaseProduct> PurchaseProducts { get; set; }
    }
}
