//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KatieStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        
        public Review()
        {
            this.Review1 = new HashSet<Review>();
        }
    
        public int ID { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string AspNetUserID { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<Review> Review1 { get; set; }
        public virtual Review Review2 { get; set; }
    }
}
