//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KatieStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
       
        public Shipment()
        {
            this.PurchaseProducts = new HashSet<PurchaseProduct>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> EstimatedDeliveryDate { get; set; }
        public string TrackingNumber { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Recipient { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
    
       
        public virtual ICollection<PurchaseProduct> PurchaseProducts { get; set; }
    }
}
